
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action OpenAction;

	private global::Gtk.Action SaveAction;

	private global::Gtk.Action ImportHashtableAction;

	private global::Gtk.Action ExportHashtableAction;

	private global::Gtk.Action ExportAllAction;

	private global::Gtk.Action ExportSelectedAction;

	private global::Gtk.Action CreateEmptyAction;

	private global::Gtk.Action CreateFromDirectoryAction;

	private global::Gtk.Action RemoveAction;

	private global::Gtk.Action AddFileAction;

	private global::Gtk.Action AddFileDirectionAction;

	private global::Gtk.Action AddFolderAction;

	private global::Gtk.Action ModifyDataAction;

	private global::Gtk.VBox vbox2;

	private global::Gtk.MenuBar menubar;

	private global::Gtk.Entry searchBox;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView nodeview;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.OpenAction = new global::Gtk.Action("OpenAction", global::Mono.Unix.Catalog.GetString("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open");
		w1.Add(this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action("SaveAction", global::Mono.Unix.Catalog.GetString("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save");
		w1.Add(this.SaveAction, null);
		this.ImportHashtableAction = new global::Gtk.Action("ImportHashtableAction", global::Mono.Unix.Catalog.GetString("Import Hashtable"), null, null);
		this.ImportHashtableAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Import Hashtable");
		w1.Add(this.ImportHashtableAction, null);
		this.ExportHashtableAction = new global::Gtk.Action("ExportHashtableAction", global::Mono.Unix.Catalog.GetString("Export Hashtable"), null, null);
		this.ExportHashtableAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Export Hashtable");
		w1.Add(this.ExportHashtableAction, null);
		this.ExportAllAction = new global::Gtk.Action("ExportAllAction", global::Mono.Unix.Catalog.GetString("Export All"), null, null);
		this.ExportAllAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Export All");
		w1.Add(this.ExportAllAction, null);
		this.ExportSelectedAction = new global::Gtk.Action("ExportSelectedAction", global::Mono.Unix.Catalog.GetString("Export Selected"), null, null);
		this.ExportSelectedAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Export Selected");
		w1.Add(this.ExportSelectedAction, null);
		this.CreateEmptyAction = new global::Gtk.Action("CreateEmptyAction", global::Mono.Unix.Catalog.GetString("Create Empty"), null, null);
		this.CreateEmptyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Create Empty");
		w1.Add(this.CreateEmptyAction, null);
		this.CreateFromDirectoryAction = new global::Gtk.Action("CreateFromDirectoryAction", global::Mono.Unix.Catalog.GetString("Create from Directory"), null, null);
		this.CreateFromDirectoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Create from Directory");
		w1.Add(this.CreateFromDirectoryAction, null);
		this.RemoveAction = new global::Gtk.Action("RemoveAction", global::Mono.Unix.Catalog.GetString("Remove"), null, null);
		this.RemoveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Remove");
		w1.Add(this.RemoveAction, null);
		this.AddFileAction = new global::Gtk.Action("AddFileAction", global::Mono.Unix.Catalog.GetString("Add File"), null, null);
		this.AddFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Add File");
		w1.Add(this.AddFileAction, null);
		this.AddFileDirectionAction = new global::Gtk.Action("AddFileDirectionAction", global::Mono.Unix.Catalog.GetString("Add File Direction"), null, null);
		this.AddFileDirectionAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Add File Direction");
		this.AddFileDirectionAction.Visible = false;
		w1.Add(this.AddFileDirectionAction, null);
		this.AddFolderAction = new global::Gtk.Action("AddFolderAction", global::Mono.Unix.Catalog.GetString("Add Folder"), null, null);
		this.AddFolderAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Add Folder");
		w1.Add(this.AddFolderAction, null);
		this.ModifyDataAction = new global::Gtk.Action("ModifyDataAction", global::Mono.Unix.Catalog.GetString("Modify Data"), null, null);
		this.ModifyDataAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Modify Data");
		w1.Add(this.ModifyDataAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Obsidian");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("Obsidian.obsidian.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar'><menu name='FileAction' action='FileAction'><menuitem name='OpenAction' action='OpenAction'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='ImportHashtableAction' action='ImportHashtableAction'/><menuitem name='ExportHashtableAction' action='ExportHashtableAction'/><menuitem name='ExportAllAction' action='ExportAllAction'/><menuitem name='ExportSelectedAction' action='ExportSelectedAction'/><menuitem name='CreateEmptyAction' action='CreateEmptyAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='RemoveAction' action='RemoveAction'/><menuitem name='AddFileAction' action='AddFileAction'/><menuitem name='AddFileDirectionAction' action='AddFileDirectionAction'/><menuitem name='AddFolderAction' action='AddFolderAction'/><menuitem name='ModifyDataAction' action='ModifyDataAction'/></menu></menubar></ui>");
		this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar")));
		this.menubar.Name = "menubar";
		this.vbox2.Add(this.menubar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.menubar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.searchBox = new global::Gtk.Entry();
		global::Gtk.Tooltips w3 = new Gtk.Tooltips();
		w3.SetTip(this.searchBox, "Filter", "Filter");
		this.searchBox.CanFocus = true;
		this.searchBox.Name = "searchBox";
		this.searchBox.IsEditable = true;
		this.searchBox.InvisibleChar = '●';
		this.vbox2.Add(this.searchBox);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.searchBox]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview = new global::Gtk.NodeView();
		this.nodeview.CanFocus = true;
		this.nodeview.Name = "nodeview";
		this.GtkScrolledWindow.Add(this.nodeview);
		this.vbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w6.Position = 2;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 771;
		this.DefaultHeight = 486;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.OpenAction.Activated += new global::System.EventHandler(this.openFileClicked);
		this.SaveAction.Activated += new global::System.EventHandler(this.saveClicked);
		this.ImportHashtableAction.Activated += new global::System.EventHandler(this.importHashtable);
		this.ExportHashtableAction.Activated += new global::System.EventHandler(this.exportHashtable);
		this.ExportAllAction.Activated += new global::System.EventHandler(this.exportAllClicked);
		this.ExportSelectedAction.Activated += new global::System.EventHandler(this.exportSelected);
		this.CreateEmptyAction.Activated += new global::System.EventHandler(this.clearUp);
		this.RemoveAction.Activated += new global::System.EventHandler(this.removeEntryClicked);
		this.AddFileAction.Activated += new global::System.EventHandler(this.addFileClicked);
		this.AddFolderAction.Activated += new global::System.EventHandler(this.importFolder);
		this.ModifyDataAction.Activated += new global::System.EventHandler(this.modifyDataClicked);
		this.searchBox.Changed += new global::System.EventHandler(this.filterChangedEvent);
	}
}
