
// This file has been generated by the GUI designer. Do not modify.
namespace Obsidian
{
	public partial class AddFileDialog
	{
		private global::Gtk.Entry entry1;

		private global::Gtk.Button button9;

		private global::Gtk.Entry entry3;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Obsidian.AddFileDialog
			this.Name = "Obsidian.AddFileDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Internal child Obsidian.AddFileDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			global::Gtk.Tooltips w2 = new Gtk.Tooltips();
			w2.SetTip(this.entry1, "The actual File path", "The actual File path");
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.Text = global::Mono.Unix.Catalog.GetString("File Path");
			this.entry1.IsEditable = false;
			this.entry1.InvisibleChar = '●';
			w1.Add(this.entry1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1[this.entry1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Choose");
			w1.Add(this.button9);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1[this.button9]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			w2.SetTip(this.entry3, "The Virtual path in the Wad File", "The Virtual path in the Wad File");
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.Text = global::Mono.Unix.Catalog.GetString("Path");
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			w1.Add(this.entry3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1[this.entry3]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Internal child Obsidian.AddFileDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonCancel]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonOk]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 142;
			this.Show();
			this.button9.Clicked += new global::System.EventHandler(this.choosePathPressed);
			this.buttonCancel.Clicked += new global::System.EventHandler(this.cancelPressed);
			this.buttonOk.Pressed += new global::System.EventHandler(this.btnPressed);
		}
	}
}
